name: Build Android APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Pristine Deep Ocean Codebase
        run: |
          python3 -c '
          import base64, io, tarfile
          raw_b64 = (
              "H4sIAAJGwmoC/+29a28jSXYg2p/1K6K50w3SLVF8qtTaegxFUlWa1qtFVpXbA4NIMUNkTiUzOZlJqdgz"
              "BcyXxeKOxx4/BlhjfA3bi4udxXjhCwO7wADX3/af9B9Y/4R7TkTkO/LBh1Sqaia6S1JmPE+cd5w4YVPH"
              "0YyRXR5ZiqrT8hvH/mTdTwWevUaD/YQn+rPSqFe939n7arW5V/+EVD65h2dmO4oF3X/y/Xym+mykGaeK"
              "oYzohBoO+dkWgceiU9PWHNPSqE1+RkamOdJpsfQfyUS5oUYbClqKjn9ztLlgrVyYloNvybutd1sqnVJD"
              "pcZwfkltU585mpnezamp0rJNneJl9OVR6/hkcH42uLg8/1G33R9cdi/Oe6VFxslGZJmmc2GZP6FDp2wo"
              "E0qekMKROZzZJ+bwTWFLM4b6TKXFwoEynRZK35P1v5ppunqXxJ+D/mvVZpT+K7Xahv7vj/5tQY+aWiwM"
              "zUlZMVTL1NQyUIKuDRWk3UKJ3FDLht9IYb/cLNcKBL/OybWi29SrbVqj8k+oc2Up0Gr5jenomuE2F2yi"
              "Wv6yXGuE23j3yea570dQ/tQyp9RygIu+D/qvPIrSf71W2dD/fTxIrwIHfnIzUayR/WTnjydva5XG/oTs"
              "dK41+ABC3FRBSXzysn+0s7/lMoeZTVv81z9+4lgzuiWofcgEuTPX6RPz+lobaoru1TFMo28pBohs7YZe"
              "tnXFtlndDSG+pwf47+5d6wAZ9F+r1Pei9L9XaW7o/4HJ/5wyHjRt8btoFHVte6oMmcKNrd9o6niulK9R"
              "99aZ7o3F4MsUuE1PfQPl6g32TqXXykx32qZxrY1Ec/gExnWspjeLz0QzeLO1Pe8drPqIOqHe8BEKSht4"
              "GHyIvT8TdkO9XClXeAfv2L+MhvrzKbUDw7SoThWbgmGi2aeaoV3Pu4ZypVMcMlN5RGU+1avZKLPkuyCo"
              "zqcIgGCHtjmzhrQNnwE2V5quOXNo4EfKjfKKj7/8qnvZOwZbqvooAokFKvFB8HX3xkBAfPRZSwif6qOC"
              "KMaH1KNOcJxQ6nCOsCwWJoBEoBj63/D5CXRetq1hR7PsYgF+2cViu/i6sE38F3wMAjX9oYXsT81bEm0y"
              "1Zn1yRCnWBBo+hYklkUP8J+dN87bg2q5Wi9XXXxPqgMoOGQgO/B/q5YfAVbIKyKGcvPUo66J4lALpOOB"
              "9wt0XUtsITBcw3aQ+BxdmZsz5yD2olaulhtZzVh0OB/q1LrR6O1B6I9quQ76fWmjkH8/5H+IvnYBUXc5"
              "K931WOluj9q258CxQElYn/yvVWqPIvK/VmlWNvr//ch/ZfgGlpTIBOjWFvAO03KIy7CAzzjASMpt/PnW"
              "SfrcGysWVS8sek0tYMDUdgsyxcEGgfKj3vlZy7KUufTL+RX66NxPTBZgd+UeY2UdYJZHpgU8M1Ri5mh6"
              "Gb/F356YQ0WnW1uq4ihkiDYHEfh8Yo6KjEneKDqoNgek51hg6Gx77xwNdBdHmUwPyIkZ/DDVFcOgKsjq"
              "mUPtA3JsOP7HK4sqb+SfUFLo1EmqCX05Mzs+jitcD6q2plO7bc4Mh1XbKm1thaYjyLM45OtzQMRCueJ1"
              "amk3ACE+AVge7Ci6VuSJJ0xFM2XUk6LFigWGJgMc14C1BYJZdFc+Pe90BxeXx69a/S6MkU/CAtXmhM3i"
              "gByaJmhGRlAfKJZAb2ANYX+iQLGg8S6oCs0zRciX9egrvvFrUVWDRsrTmbzyTYlps/NiYEA2B1vXUPuw"
              "znyJk8eEX0EZ4XUGoFwMEDug6cpJjkEl1k4ZWA9Yk7P40JCjOSsMLlQ/ZXidmcV0iiAqJ48RPvpdqKIq"
              "dFBr5hhgUmXZ6Bj1LTE2Vi/YeO6BxWrKhqXZx8YhFlwQ/TVjwNpfkgAC1ROBtRAB8Mkuh/6xutIhcZq9"
              "4JIJeRR1HnOG+DR5cLwAFIVeeAMDIduQM9HJ1Jnjx1KJPDsI/Jk98vSGZRNQNRttt5bjYD9Bhp2OgKLe"
              "QBEVEbZ5UVBSNzq065kBFimYOWonNMBi0PqSjR36lL7+glSFueW1z1iHkEZFJiGAAIWQ88Qi/xtarQR7"
              "RqFkmLfwuje3oZvycGaBrGH871TTdc0OrVaYQUItqBv9HGECaEu7Q/KKyrgFFPTG6hX06Nc1ycNNCBrC"
              "WZ0E6nCJB2+ZhzQyPr8OTvwL4kOM/BHZq8A/VdCHA+SVSOhg4IHpbQzngJu2PVCG6F/1OIaHB7LVYnMq"
              "htcmuC7aNfG/kseRVcMH6Nldck+9ETMuhQpa1JlZRsRYX3jtgwsRgmpkHQRM/bHHYRqAhWwSHqfeForZ"
              "+Q21LE2lroL2DLuZ6XoUj4V2CF/lmBgqTHVlaoNCaKdOn+zEkD7USlCxxJZw2bx3JW9EFH1JE+Xt+XWx"
              "uk2Kft+7ABx4SmXHRIZSKoVa59PH+YTggLy0GOmp0D4/vTjp9rudAu+t0G6dtbsnJ/BCcCLmwlPVqBLu"
              "Pknvuf8xFUower4yxdJ2rK6nzKc2Ea8X1vWRA/MX8ZJBxd9lIpGlj1eKmgRQcaIZsEBuN+G1lQwwsjqS"
              "cUXMBxxbWMqWbe1bGqrnI0Bg1ZhNZKrK/CuKTsKoRVYszOHZOT3dUVHn5oYXyrcOd+QCWoF5yUpipSiW"
              "idXoKJo+j0tHfDv4gdt7WDjKZWKsRqiDL9LBHJGeEXYelgDJsiHG6QPSIVlurJnPa7YgqRYrXyx5jC3C"
              "5z91Z1gSvDoym8X4NDToASYqM/AjtvT0SQgM0WILiRdfxESGHRY2gWIh8fFuSzK48PrJZiFVIJ7GpaQg"
              "1JDAjVRLnE5onGysnLXePbDebSUNJYBfQKKXFD2IwHgZKtiIYqjyL6vfic5SUYhLscrJdpiQdrCXwI6A"
              "DFJ+1Qh9RivHKanrUuAFEGAaPeF8OX1KLbt0Sg4rCG+nmsUFT9gU89sQRSLWmICiGMXnn5Niin7x2O0n"
              "xj5GlmI4oXkXVYl5jftrwTUKMrEQ9HNxtDjG+makbN4pMwMlMDLesCoY6SbIRDkUZTZTFEhhfUY3RwcB"
              "PSaqH8JnXE40W70yXHs5nTnYzYlmB6GG5cvQQ7Gyjb+HeSz7iOIbuE4T2A7726IT8wZGG/i6Q6phvFIs"
              "Czf6XF9soD+Q0UB4MFOiGay9KO1hdfPqJ6I6d9hGVhk+44oVCxqqAthYWVMTijB7lRXxdLSEkkJYu8XD"
              "qllCHdf/wWoEVbSE8h7jdOtENbSEelz7civxvxKKAo55BaPKWbgKLBKrAlVLEq4s91b4vjJcvAF61qE3"
              "bMrXjxO1hShWAicHbHzsv3sawWZsPu6KkY+BW0tgNgjexDwxEWxnFAKvUBH2yeH8OjiEQHHHmkuwM4rc"
              "2H8YshzJEcMrBMCusTplnRojZ4x+orhw9bEeS8JMA8ivxcUrzoFRbexLlpUTsnYQaQJQxRiL7cQaQRtH"
              "VOQ8E0gspVrMxBF1mR7t0lxK/Yjhg7XNacA5yrT15OoSEyg4AJ8gU9rwjKAIvARVpg0+bh0Fe2e0WpLW"
              "jr8tJelRZKg4wzFY3Aek+3ZIWdhEzJFSnsKYYeRglPUtZUiLpWRFDLErSrpDkKkWp9oEQSwEg4w40xhC"
              "33QU/Uh4p3CFkC0ce3H8gWHFZJo9m5xfY2CLE+Ojcf1KBKKwQqIZvib5+xuyJWT9uSjxJOSUkHUK0n2o"
              "TXXNoD2MA4n3xg1fAII7Kpn4DtnQKJojNZjvTIwbVA+5/4Y3nASFsAAX7tgLaig6i9rhFm0d1ASpx/aP"
              "QEMLtXCl2HzGUDdgMDDNqER2w1OOgl64kaAz3i3U2Q60uBMdX0mGWa8pfaPPAeUdX9RcKJolPP7buA5P"
              "oxIHVL6ZHpcP8XoRgNnq9XJei6240Ngjqnlr9M24pceWE/rxd6Db0KChKhbnKYCWRoi2GQtkkkJSpdP6"
              "ZnB+NPim27rcJjsRMYNdqTAR7o6B6bnulSHTpGSF5yKGLQ6Fbreb4bRJanXCfY5Sh40YXthfw7EIF5FN"
              "2x2VY7KmUrger+RGeW3id+4p/oex/tZwiJyAhwj2MFZsSPOEAmXE/9ablWj8T21v79Em/ufBxf8oQQSw"
              "BQLIsCIpMuiY/Yh+xZjDcNvhRrs3WEmEuiRiIjkgstfFaPCLDv9ohuYEIxlE4MxBJJCGCyrT3exAiWUa"
              "ot22CTrxEIRlSNWyZ1NqlWWFoh5h0QUy4nDwjjPWwi6YSP9x0BQp/huZPvvyLLqRx0qiIsLtsMiGHFNy"
              "5lOUDqxgmf2LUc1hrQaLfPpE0l+5/81Fd/D6+Kxz/nrQ67f63UH7RevsebdDPv88xPzztdFzq0dFbGwn"
              "MTwHFocstja8yQhUR0HzLGAH+8ZoeJLhNkC4+dVLuSqEIult5p6aaQXy85+Hx8eIAyPpiwVdmRnDMbUK"
              "Ja+HsHv+4CCMPWV0jmqOpuigeapRIOXHtAgMsa9YR5EtBHQnfioZDd8GkX6Uuk5lLvVIzehWlQewEByl"
              "FjtQI6ouz3XzStGxS9MoPj85P2ydDFrtPsa0vzg/7Qa2eIJopDFuBXDjbIvBa5sc4mjY6AFjDw4YVyqj"
              "5BT2k2QUYr/zSFfATOCNlY9OWs/ZGF4d978ZnHVfD/qt3lfEtBLNVPZIa7dPQDkc9M8vlqveOz57ftJd"
              "vv5l9/yy08UBDI4uz8/6clt5OnO6bx1LKRYOT87bX3U7g4tW+6vWc9Q5wwsZq/5OvpHiLkKRL5RkFSOI"
              "lOLJTdr5kPNgBINlzXjszAeth+bU/07hswvuBaO/M/S/arUOGmA0/rva3Oh/D1D/m07LLZ1aTgckjjla"
              "TMtzv04n5Vbg+JZxbaaUFCzB1cciBUeWMh1rQ7usWsot0nS5I36JlpxQVVPKrZmqmUD3lnbFonCSC4UD"
              "zCUF0D33JvrdtMuHM0ONdw8fmAOmgx4DsKBjM5laJkAfWFRP5GOJFmBx1V1Vc2SzYx/78M9r9DHGW2cK"
              "9gk7GgTwRgVYXuQV/JP44bllzqZy1d3QJmwxyy33t5eOpsfmcKupwOUBRI5jGgkf22M6fHNovk34jBDo"
              "S44eiM/HE0AT2SzE9xPNQAcpg0RCEWw9pYW+qdjRqoHDYJxEplN+ms7lmLHywdNWsrHJ8V1e71K8Cw56"
              "bWcmxHvvZLch9lfLzhj0PDXyHdofl23NCB21AGggkR+DtPXPWgCYUJGOH3QIaNnxjxoM4IC4NP7MP/8Q"
              "FE9oB0YXYHUjcHeX9M0peQGTplZyU87NKyBRtGUOFVidA+KhU2KVK8doTa40AGoPWISaswpykfPrjjJP"
              "KM8G45Y5NlT6FiOMYqdAvCKYaAddeDrzpBYL//4Pv/oVOdNGYwcPXH73t7/4P3/4NYFy+Bd8+0+kNzNs"
              "6rgRfQCeluFoO6qGBxGZnk2+npluqGMCrA5xX8li5XJO+wwKpZXHYgJFWbHkmf+Uje6EbzOKWXu6X+H1"
              "WNMpAVIk9tAydebhBL5u2/p8G19bLD6BKLBw/PyrYlGizgFb0TVsQ2VjSMsFf8+p0B8rDjFMR7sWko/c"
              "KjahxgjInlpUJVdzMrXnw7EJkhWGY6MzFGxGGCrrb2qiTAS5G2rV37cgmk2gsmnjGK6oc0spdIGd4ixu"
              "FcNh0TfASiJvJ6btREZKiTnEYBbVBJyAMRNrZo9h3tRBU9qagyGEE4VZD9megWaPYQIwcZXSKQxa03UD"
              "YBUeKX5iqgWryD0lU/MWDFOoCJ2hFmJeE3aWFccFgkyZwhCmCsA+DMvezLrG8+SmAebW7Rgm6sCYJxoj"
              "2+i4ysBGlDl2goXYCJWrOY5uKxDcCAh8aIJcmpAz5UYb8RXqK1dp+KtcHXJCtHDfIiBZMqq0fjpTLG02"
              "WawW2yJZrMqFZWICj0glj58pVwQJKGWKKGfYBKHsAUmnTizrzixncTalnGXFXPzS3jRwfMCOrnZsyhiP"
              "ncpBoCC00Ub9NifP4TWY2Y98Ik8tfgybddLjg8qaIq/hdRKu5U4VmTTp3WpcyUsbM5ZE6Tl0ck4SKxxZ"
              "lB7p5m0Kb9Vs3ipGicJ43Qh8d4CYcA0WA7jSFCaUxvp7VGeO0XNrBOqjPXml2TNFzzNY56YNqoczs2CC"
              "wDNyy1nnxu2LKxd5ajDcYpo77vXlq9OhU2cMcgfZvGnlxTH0Z3S0GxiXUI+zcItB2oVEW7HUCK64oaWk"
              "PdamdmwhbQH/4J4+BvA1kzseYkNih9ad1FOvPxe4yV25JTA/BIggnRa8yq7SRC5MzQDR9znpoKsGARhv"
              "70YUFmWfkMZ+JVZoZginIfA9PRSVLSvVMujENGhmuVfcH8gLeYoP194IU99Ib26AnLE1O0kvYcWY+SjR"
              "SwBaWJ99Bj3WszTdgyax4goWuZwZGHqbMHwdc3AYKmJ9WMP7zS/Ja+WGRU/CX//8O0C9K9Crxd+g/3Us"
              "AAr/6zf/mZwCjgT1vekUF8pjWeTCoqARpnBfDJdQrOEYax4Qz5RLLG/d8JIhCyeF8rwAnkV0b86IWrqe"
              "TXlQuo0BNkmF2XroOg4jpFc+DphAbkRCsA7INQdVwIUqhkYG5lRLVaYOaiJQBxsRf3vLxWRtKt8Kh8Dk"
              "F3M8guM5+mJyqyc3fkDRC9Bu7Xys1Y+F8Q5oedXceQo9ATDzhQLKeeqUWYncs7VuMMwnLzq6yMLrZKGW"
              "c9NlgZCscHhOQUxRQUIIhTPsT/L4g8xbzaQELdpA66obfYLowIQNmjXPZFuYibVCR1Lb3FeHwy1eljlC"
              "lBVhdg/Qq7zozqe/CwXAYfpp+JTubMoVdV9Pj37nRnrLULkFGv0shLrhgGEX++gKKZSosY+uTGUiNfrR"
              "1X2hX194xYbGcDJWVRB+9L2Iigq/5LFmfpIGdJhdUEtYP3Yxbe/4ktqzCZXuWLufvA+zKUbuMGCxZX95"
              "HIqJvwZuP2YDlH3AQYbe8w0bD0TCTZg+2g61YY3m0uF63wI9mNOgIyXwySObZ+UhorEe7talMHbAw0e6"
              "QK8Rtw4KWs1Qsdzh/FgFxEcnbLiM33vEwSOtHCkTquy5epJqegUCxBNyriSMN1Ai1KHnZEnq0CsQ7NC3"
              "huXd+d9LkUouWqTUc4tEqzIETKnHvkcruSIiuZooETz4GLCEpRWDBUqhagGjOLFmoEy4smsiJ9Z0C4Sr"
              "+dZyYkW/SGCaYQM5af0DRUrxqr5GmFrdKxY45hIzm6VNxItFm4ja0SnNRIuGgeHb0UmT8UuUohVdezqt"
              "qlsm0G2SgZcGi1jhAM4n2NoJTEFeONhc3PxOaCpeMNhM0BpPaCBYJFg1bJYnVA4XClYPW+gJ1cOFwmju"
              "GuuJCO4WCKxq0PiR1gsWCMjTm8QK/FNwYmEDKGFi4ULhibm2UOLE3AKhaq5RlFTL/R4STxFzI2kVwqWi"
              "dB4wPVKoI1AqhEVhEyQJjcKlwnQVMUcSSSpSLgQI3whJqO4XCKLFCT9CKEML/BRfoMQKwQLB6XkWScK4"
              "vO+JypRcGw/oVUHlBe9+OIeRaMM3qAtTUE0ioVSx/axi5M0XpFoin0U2teKZDUK94i4pujFDdX4cbvhP"
              "YwHvV+hsYTsPkTHIgtCqZOcpqbw9Oqoc1Q4b+26GDealE17S4FNzi9c61cNGN1icb7rFD33jCWe3j0fV"
              "L2vtYCW2i5dyFj64to+ZUy9IPH1TrGAJF+hQGb4ZWaiitk3dtIpXI2kAYVBHzF5X2YZdMf5SrK6/cRdf"
              "2ZBO6y6tX+HHsUb/VB7uFUPiuMkZmAMrxbzyoNYUNWw3lkUnqkOCCmb7yXbZOXc+c3ZG6BULujjuHR+e"
              "dPnqsjfPz8+6sRYDqmNKo9XFGnW1ypQWa4u16KubKW3W09sMr7VvUJQVfTpWJHCslivXvJFKuXktqe4C"
              "T95CNUcLDFLy6rUc1QVY5A3UYw3EQmWDY023saW1aqVkUz5WuF5KNO/fSQ1BKekHSKVSCrCiyIJkVK3G"
              "q/KVyKhXi9dzlyCjZj1YMziHVMYRcTaFZV/AjsrmknGrJ0xIQcKRVIzaOZLKMbqND9Hn/3irE2b2Blnh"
              "Rd9djQZTLagcyhtB/yYXHyiw+BNPOyW3KWVCqJKnUrjTLxut+uF+vNN3W+mtrGGJYlDOvT6yxc2C0OLL"
              "lAK1XEslwZX0ZUrAi6Ql4vkwFLXFd1qKSQqIb5hnL1zCtnZkuOEWl4NxuI2FwBt0F+SDb7RGfgCzMMfy"
              "RHlDsY44+VAQnhABpQPc53ejvWyQPvhRnxMv5S5v5KR79rz/YtB7cX7ZBx1ybN4WE+gtOtxF1yyexygV"
              "aosuWzIkcyycDG/Sli0JRxZfNBz2Dg/ruKDKkF7PWDo/Q72aizAvXMM31Mq7YkmO7dyKfmgHvBh/KRR9"
              "f9daasKFuhaqvl/lx7Fm/zSm2EiGw5QcWd6uxL2F1GxcXCNLqSgDa5JLLxu+uFRujRPTojxMvxgNwEha"
              "TM9tlYP4cpwQkwJy4QM56YexThVnfDH79luoLTuRlfPcUP61ROi4+dVkITS5DhOFlET5kpliqdwY6GgC"
              "qSJeqrNNVHRSYkooi5Y8h4RbNwr/gmqCkaEZBXQV9C1tqlOMAvnL/0HOkQ1oQ9IRBYBr1CqT737xN43K"
              "hDBHKL66AMRE5qFMwRygLFCV+UbLGJI2sVEnvkb+jwGwM0NHrwPYC/SafGsalIWzTi2wu0GAqH4s6DX6"
              "xzFPB1B5JMlK4SdU1+eR0f7+38ihZuozjAm1h4gRP8JS15rNxtho4rC/DA17bNrTMUCIF2exn0S9hVqA"
              "gORiBqttE1Dnx8A9TB7ZalDTIMO5gklWcBYw9KGiT4gX3Qxl3MBUMrNGkrHDejo6jYL6v5LWt7DQpEcV"
              "0uclENZs0M1mYNAtvLcGg2BNi6W7ACga3PmA8P7KQLc3pqKYGbfKDUUMYbHC6pzgJT4YfEyUoWXCTCdg"
              "2tgYWGtOKdokSmyoQ1gCgwEwMtp/JG3WfdsrACOrMsSoByH8SrvCDHFEEVFUHnCPJ5OZgSdTiTLCA5sO"
              "CcaH2+ygC3HGIAxHAP058EnTATRk01U9z29swDAJWE87Ct3f/4E8N3UVZtlzC8DgGGyrEdjiV3KtWRNA"
              "VwyzhuV4Q/UpUWcMlKagByEg7DLpg+QcAxwtUDZ2bFPXVD/MmcVUM2yOjtT1ywVg+mfkUJ9R8hrj38gJ"
              "vdGAgSmM4poMsLVmELIYim3jrjjVRgYZaQhlWMpIIDNBrmQjhzS9TxSA7eBVDWO++kB66sw9IcGwfQJc"
              "EvcwMFuUZoTQIiAWAse9yod4x1Xs3DDLmYd6igbozPhS/NspgAkYfrHAZnZAfsAY19bWD5BzbW09t8xb"
              "GBHbJzrgP0idFFvIaE4VC6mMnecw2P6cFyx4aBp4V8YXtQp5dUEAo3Cf302kgyZUIT6SC5PfPcgDcooF"
              "wG2GJ+w8fKS0r/gkWfeRaJEIk2ZBjhHnedDBOoRabgsMIcLJagS7ztmA4N3hJhgHzdkA46Ph6pyJ5azP"
              "+Vkkoa8e359Lqu9xmUjKHkHLOVtxST+wxcJXC2W1WwhFpHe6iADT+onm/2kEjx5xCSuTwlybiUW2QssR"
              "j7R8Q9XVWFnnkRrBbU+3HI4qUiy8Q+kW5JSVbRYAz0BWN3TpCogS+1jYCGBI/izBeRaGuoj6ZfGkf/ln"
              "+DOJFwo2UQUthHz3i9+QFvI5QIY/wXjUoB9O0EjO/lVfv0G9B39KVB/ReUP03XN1mVjnjLpyds11Gdbx"
              "7/+NTT1FixEj+FKM4FRTDTaCPmPooTFwEs05CMdTOVAXYbJQoo6I3lEfwd77t1rC/Bl15+x6GNQhULfA"
              "nxL1QnReE533ADdQQ+QlL0ExCI3AZQ45B2EH9ALUF/CnRGVwsU+MoY30AL2fKCOT3YOdvlUUCRKMyIRh"
              "tRnlZF4sveBmUA+6jjDSWp5qtVi1Rp5qjVi1vUqOanuVaLUv81T7MlYNyDwPTGrBiuwwgh/NDmDdRiBt"
              "45S3cQLbOJxt1rhUFuDyFLEVP96W5bGzpVt3CcclJsELQrxhYba0LuiLEiNSk7h06vuHnaMEl45fZwm/"
              "1bvY0BZzXUVjaFwRw4WhmxOu8Fmlph5UKoXtWO42f7WqzVQS5YuBa1hthjhMLU89XPZauF4jTz3ElEa4"
              "3l4lRz1Err3Q3hWgWo56iI9fhusBduYBTA1qIiKnsJ6od2ISyMwdCqANe2BCF/aIOqFMfZHTNl88IbVK"
              "UlysiyD8NMkPIlVfXRS2IqodS5J1LPXsiDHx+GNeUO7aETPgyb5CTQboPjWYWa4g/fs//OqXzLJyQUau"
              "6GhmfMoPvkS83eVsvUmyaLJRhe5ikoctL+uAC7n4/KX6u78i3dPu5fPuWfsb0nt5edRqd0nxtNV/Qdov"
              "Wic4oW6pkNySzKcNnKXTru3V9nzOEouhsdwrA9jNN5HJyK4UCLXgAYdn60W3UvRQRDHQwzbL9S5zSUaC"
              "zvtAhkAImDr+JSaFPoIG8Bgxv8+glJDdiSXBZAIhVtG9WSexHs5e1iP5TFzJAy1UkxpYhEfjP8ilt4kt"
              "y7GUBRk+rmISCCILuNBFFJkkGs79lhKwkHUOIcMw+mEwkwRjAn/xf3Em4E3iU+4uJT0gSWemWHP0Yc4s"
              "tmSfRtnAyfnZ85j1JJfP7zgvLmZcXZFAxMirjl91yfFZ/5x0ut0LcnTeftlbnGwre4d7ncaaFIJ0F3m6"
              "Hp1wniaiT8OUjmgs8vIxd+889QIcsYzrZg/HRuKXZ9kbHnExWK1EYLOsKHSnAmikOBi2A9XCiXTKbL/b"
              "fSUE1CXLu1NmvsoBq1vKFdZ3xQ55VkvPOL75zXr9L9JOLbWdHH4IBh/h5NO1a0AAJLEvqpXooeCFPRMY"
              "XukhDts/ssRNKI45GrEjglPQo8dK5IKj6XOwOamZ5bfCtkXJsD0zbTm6AozcztGAWzTSgndqOaM6Kxft"
              "3T/LnNU5Lxmp755xzqj8KqxgMXfhjXTcEVsOHVdDs8dSs0vG79wkTCClGelEgCAlM0lpJTIjFw0S9PMk"
              "bP71//zuF3/+3d/+I+bL6c2MN9QgLj5xveyAdCca8ICRqavkyjtxnYzbwds+XHxZdFB/h8PhlVF2XYC2"
              "oQBReCMyxgq7/NnfdSHKzFKyxuUPjK3ks3wbx5+GDufL9AksFWGZT4Hj7lcS9a9w4R1WWK5mRBIDxAJ9"
              "lmbo8kZYP15lljOzm142ZqNXKkfNJJGcxVz/2+/JScDNyGfd1pUJeSkA8Wk+xpq5P548ijMU0LAeuEvj"
              "mGIFEoa14GCyoylcfrgobro8JTd21hoLYCcUTsVOnwfeNX6KnnJiqFt6rTj6qz+QLuqJYFEDZzLeEHf2"
              "RxoFHnnPiApLE0bU4JDWj54odRbFTSapciNmvbkAYkLhVMQUMvWusfIVyzGYCyVZ0bXi46//xdtwejFX"
              "LdMZUzBsdMLmfs/YCOsRxsbYiNaFkmmORdmhguDxeOkNXGu2Z5ir5FaZL9wiRsgMsGa8vSlG/yzc4FVo"
              "627AGonYOkna84QZOnyzf1UDjLfl7vuvpzWxiR9rzAX8Im15W5rx5jy4L9KeHyCw4vDu0wJe8/1fiYcs"
              "RV6R6G7jVTVqALkJdl1z7opVjdwMObyq5atXi9ar56tXj9Zr5KvXiOzlcaehf0K2GL+LyeIpUpiPqBKP"
              "Ab6qPitrdtstIjyUbp0vvpDUqC1co75wjcYCNRgnYxkKiu5UvQu8GhEnlQ8qT7z+AOp+BrYqu4mjIN2+"
              "QyBxFYW33wZzcUQDhudgmwww0k2yHoHdLoTcOpqpr6eZxqrNJLouvXw+wfvq2Ml7carWz4EkSfscCbDz"
              "k3uhlApl94JBTt+MtolmH3KtBIYbF5rUie+vRO/U8G6e7VFHdgbQ7aCEzbE7u6DjEldq8I24VhBfptxB"
              "Eu2WjSt8NpkDG0HFFEj5DYgclIoHFR9EW9J8Bjn8u5iUWtcv3rDj7oEsbiB8pvw2wUBqavIOL5CJQSpz"
              "sqKH8AWv3thxlB3FUYrRhHDbbsVSblDJ8jPkOECQNQF2XWt84rnm4NddYhq7u+TrmYbWWCDLYJpwnrJy"
              "PXOoKfop5u0vPcuHBW/o/Na01GCqRAxdRl9YAbMO409HwxtNC7ahTNmftxpLk/0W/4E5q/xPJOnZFatg"
              "s3EUJDfnoVbAczcGkY5Dj+EdnUSJGh93lKCRgu5N3iCfYrcJi8zq/iU5b4A9jAwTz5DYrkOhhLcQ8QuU"
              "faTOqhLdrlonYbhgWByr3Jp5cSrN8Pubf2Vn24CN/uBnbrvs7NE7whGJMExiEQALb0ekI+pzDMIerYCj"
              "Ix68iZf1sjhDgzrXusYwEuQT/+awU8v4m6rZBruTsYDHBiYMb01YlrcbFH3YKPoX/5KIol3c4ULoTNBP"
              "8Tl5jpO9A1Q9Vd7iEPLi6scjVdPW5bf/nQBctMlswtaHp4vGnEg/+JnoRawS3ia94BFZaQ4p1MGYy4tp"
              "raq7AEUvFiZwH0xkVUJxHVf0Gqgo0FLRPiDwq9WjP53hQaJn29wHxCLJtgm7Xln8rlyzjLM8wuzdVlpU"
              "Te72+Xhinck8mHxB2SFwO3ixfUoQZGhYbPiRkblX7DwLzehdYghX6CR65LLFIL5r9pnpsIxJxVLs+kB+"
              "mYqEdqbomJqG70CKlfEJYTrxLhjWdYbo7jVLdjF8k1L5ebc/OO32W4NOq9+K83yRvi98vbIkG7G3FHgt"
              "MqA2Hv5zB5TkocYrcoJUH71bEXm8Zkj8y+wYqN1jNymisYsNXeOdeuwEVuRSKX5HXe+bXr97WsKbJivS"
              "wXzqNpgW2WXwFHUcvIF+TpQrquMwSgH0S2wFb6+RtXIM71kj0posEwPaW8F7dPjpzwggt1kPpfw+X695"
              "27Scwznnx65w1vFqjiEI12JUrFoz49x4qfVlSMtYbywFdgLlxjJex5vKw8XT5UMcHOkMPodLPMB3gIVZ"
              "c9nxIMkMEd1Y+TJa04rxJh6hGQBdehSYTBGTBY7HVC02gGR1S65sJVZKhdxaFzAxejawjlHnJ7vyPtPz"
              "EcotEE2P6DvJeGvmNRfoHvC5UBfyPC15TCDe9p8wGMPPklrkbYsQ2ySfksgFHXQoyeIgJdWj5SJgskXq"
              "wXgAbiT5YrGUnL7RhxNr7rNIpLeDSRRP+SXx8X78FIsiRLAY9g6PWXJGvw0MqA0VENfP+yU+C5aI5XB0"
              "B4sEiW0/xVRhhR/8DH5/N0a9Gpp4Nylwuit4f6dlfvTn/7P4/LxSfrUZ7kq+4wd3C1vJWS2FXw00jGgm"
              "dHbAlBWUwpS3EU0gzs25t2Il4DewHPE0A2+ozF6cW2cz0Ft/xs+dAA9QgQU9O8ATDwELAeV9UVWAK1yL"
              "hQN5D8Kft1SS6DJXrpcz4vTk3s7Eu3NNCw/CKyKLb7Bi+VX3sn/cbp3E6ows5YbnTQrdU/icvy4fnvf7"
              "56fQsvxzu3vW714OQBk//pPzs76kfb5MF4qlTOzooE4C34oAWu/qxNCX8mmr334xuGhdQmfbpHodZaUy"
              "8Ik8UBkAYxRD8cTeBUukWPQWCJSUI9yZwrSQLhr470q4aVCrwL+WOGBkl1V+kc8pxdgM+JMaNkCo5G6r"
              "Lw8YqapTrO4v0vu2tBGO1MXFWvIAFp+SJIdIQuB0SsSBZD2BhbKM7m5AYsaquqd7JflCF8oR5LbVA7lF"
              "MIj5elHq4eQhG8UFqKmoAgPWFxuLwb8SOnMkAZnHPVAXZvCCN6WMIgzGJUmytSCHDbTHq+fdc+UXMYR2"
              "ePDVEjs8wQy82U6VfCkZwmkZCqx98gJaNK15QV7Uy9LQssTdhzPxC7soELOgsFbYfYQ8fQvLuDDmrT5L"
              "aDaecgEaKZT8DbY8x0mGLnxWOO+ReXDknXT8ZxRzvgbGz85iSXNGRPNGRLatJGNM1tfcYhF1TecJmeMS"
              "XygXERihjoNVwObwvA+RrMp+IuecOQcFnmekNpTaLemdxVIjJvaUMix/VxD/FNYHg0Epb7RTKGFX8Oxk"
              "chqwyD1cofg4qXsnHjPlKeQKqouXCrt/o1arSCLymEIwu74WXNy/JwwRAcT6IXyjFn6VS1q/C7kQDdyB"
              "XW6/aJ2ddU8G5y/7g9Pzs/PsGt2z9nnn+Oz54KJ9OqjuHR73c0hVJhNFTrjAfFwGJ6doJM/Ipd7yCXtD"
              "9AtmNB3s4iVji9H6L3ut593Babdz3MpuQtyT1J9P4w21QcsEoTrof3MB7b3sHbcz2rvCkSeMOwNQfIky"
              "gCTWMT+AusbQZKI/HQ2yG+p5iFn0cTQHdMeY9ls/Vew3xTTcvRO4+sR2bBzOEQVd0kyok9SNf/Uf4yB4"
              "wXxMdWNEgbpUsbSVyBb45VpjE1iZZUHR5PGwy+OMEUvyUynHGc0tuwe5GORuSY5SZhJqaAPyIZQ1TE0j"
              "dwN7XJN1jWfKy2h4YDa/8sUxGiL7MBqwUnwkSGyDGcIKu4yjaGtGkbWJxky9UoFGko2VkIfX1JhXq1hk"
              "Y7BA8zUnwPt3MO22sIxyNcbn/mPtT7ExNqwveOPMRYxLklD5nTy8ma33raUBQfCmma4sIGxL1/RdAtag"
              "9JJ0zj9aFBQsO+YMzRO1mBW5mDvQOCpcA/0kXnMpF6U+JT2TTTv4OT7xpEkH0s4ECdW7llMyp/jlbBFt"
              "jhq4v6KK9AU2uxPPYXnxyj06BPWbaXZ8ZyGczYPLE8wFot8AVoQ+RtvonrVAWeoMWu12tweK0/HJcf+b"
              "Qa97+eoYXnhVS+jmKRRkORpIaI8GcLqwW4B/mU+txQIHhYImSdWAyQtMQxsq+lkwiRXbfYnM33c5i35j"
              "2upSxg87Hs3GinuzJDRgckl/OtMsqmYZRX59g1LVjrQCxpHGLy4XOSFCySLZpq9ILsgNJ6G/x1IGJhlN"
              "XQYo5K7u4mZaUHINM5Q2w8uEKlJveIiDRy7Oz2II0++DPO8lHKfIzSzyMo1khpbPUDsBMrQWtNPebQEZ"
              "M9yNhFoWY7fqmkafnSM+IEU3W9yhaQI3gUnvPCUvDc3ZKpHwfaFl0drjcONl/PYCM1FZTz0eEbp326ET"
              "O/eFsmKLoycCP7EGH+FTV2sQTgy2IWPQW2zIvdo52Pa229QBop3bSGifWwzMbcT3aQTHIP7wPhqmo13P"
              "sfce9Xbf066C5JeR+lAqThXMzHngu1e3+fUqoF/zeAH+iZeOMF0siOYh88jAXPEmVqt8bYHE580yNkTf"
              "OiXQYdhX/2pTnO8AyHnAprRNeIVtLpGC12DiBn9gCEXsNG2GhyLmRhQfsx/BSUBfjCdgqr5IQATbXeab"
              "4mw9fuyW9HNe8/bKzk0wqWAwGiteUuyQhQoHhECIkbOPbIP7Uy4Ro3QvWtVucLcbifV4Au10RP4qv35G"
              "9gt5M15GLNdhGciMZc8nA5VeszWLdBDeo/JjqJ8EkNeXSNH5l6IQG16JBoKR+36z0eLYHmMJuaKoDH4n"
              "DwriT5P7k8FKPiy3vXB0jOBosblue+Vlfq1YR5kzSukoedQJ7psQHWH4CzQpNtgYobhEwTd6WRXO3wPU"
              "5q4Fp7cY05aUjJEfw0joEPHxFWcw3grHb0/TcJ/5eBhNHcHJ089Il94I26wOo6JIw8ABulA7ok70XM6h"
              "y//d8zjpTXkVSlFpGnTGBaWozq68ZpLH92A+TZSbgWakQvNByw2h9A1gzg9IcsBoULMAwErkBrMB1Gs0"
              "TDQ0xUFmU+FDKpyenhJVBZIdH0wmBAPkQT1WdGazdOi1MtND20+eYME2vBsb1Gs3bxC+Rj9tGW/Uw6zU"
              "U2llkV4zsOOOdbz0TCKE4N2EK9rA7IoXOnqHAId50Sn/0ysYyG3m9cLiOzj/CfcjJIMXJRIO6AymxcVU"
              "/FjDZslFYsn42+enFyfdfrfDspjHlWRvKDw5STgaxa+cr17SlmW70drrJm8UJrWV/6h1WFEveHnmBi/P"
              "Ts7bXy03ez9b3UWr11sNBI+Oqp1qZ1UQHLVbzVYzDwjclPALTrl12DrrnJ+tuuDVbu3L+uGqs03bX363"
              "tJBmu1R3KqM558kvFUHWdEIqj2hEcKDFGhKVYsmOPEazUHN+tWiDgZVbqMVAPU92f7J5PvYHpNeubQ13"
              "MVHmLnrrdkGS7t5o6niu7DIJiqJtN37PTvmNk7cPTGK512iwn/BEf9YeNffc3/n7WrVRaX5CKvcBgBk6"
              "wqD77+n6C9sL01uW+aqXvVXf2gKVz7QcLw4IA87d9Y9+M3FD1VB1Gv1wqwFLwc1EdMolfMRTF8irEj67"
              "bCzpMx6icb+9MR1dM8QOTvmS/XBtkDgWgxTxfKBRvxsq8JqhOcylFo63OHDTEwcPZQQ9cEPTsvDosWHf"
              "ss24SopXq2grN1RlpzaMIWVW9gHhsHwWij6YTUE2p9QK5ET2NpxZaJNnhShiroMpg0IpISs024YIvsDj"
              "Ce5xhbawcaK5/76egdKuxdMmxjLu4Sq4hcPSi/oACzXhoodoAo+gOWNetBTNBtqbXU00JysfKC/lNhFq"
              "w5hNMGkGx5yyAd2imlPd3ybNZilasiYp2dgmjf1ApvoIKrD2/4hVDkQUuwDxNL4e7uvgtkJvZuGxY7yf"
              "A2v+7//CfsGOnxW2IhHnE83JeSiPBQC78GadBo6wlOHnpCg2O3k8sCQnAGvjSXh+Oe58G+FdUd0JtUbU"
              "GM4vgC6LtbgmKj9n991vWV5Frzap7XAzjmA75Dk2jelDBcwIz/dZXigr77VIc5zvVriEcf79r0CrFZBB"
              "YANoPiUdvLKJX7nIdoh4emo7aZTpiZzCa8fC4zL3XN8tLf+ZV2cJ0Z9H/jcq9aj8r9RrG/n/Ycl/sSFd"
              "5juJubUD+BBO2r6M+uDpB0LOh7D1rkQ8eqmsaMr5Z25AwMMS98xrtVZpj7PNlPRsHbCkl8o/Jq4PeRBF"
              "qrDGMn3Ty7cea8MXBxkNeQV5Er9SSHweKnluYWenK0w2d7Fnzn+4O+anreOz5Ch+RVXbsHIj03K33Mvt"
              "Vr/7/Pzym8GL89OuRBqx861uZ/xQK8uHiBvyZ93Xg36r91WKvym8zY8jj+U2C0u7cOoYD2IL547JcbWr"
              "NAQh172u+eew2kUTTsYFE/ywCV7OcLId7KYkv25i5asmAofdFrlpggfyDJe+aIKTe56rJWBs26yr1MMc"
              "+S+WkCtj/kKH7kxI2B4BusakQTZVY+FXy1HyYlS8GAW/28pDuSGwyKfdAXvCMudFmUjxvoURPXLNzMYB"
              "uPH/ufq/5Dam/FZAlv+v8agS9f81a/WN/v8g9f8zDN1ylUMedp9VzNWgJcUELiUZE0L7XMzWcL9OJ27z"
              "GM8mtUg0XZW8P8Yd9dh435bZQfcYDPACVce1PCR0QtCS4LeTJQQpYHfiLvoDISae4bYYH0aqScGu84Eh"
              "TJR4E9tc9IhUOkycHKtukAPuuYWz1TBo4JnqHki/cq/z1eD4rI/5w0MfBu3zTrdXPped8B5ydIDxSpCk"
              "WGB4NRCFMOOYH1HLN5/gnQRtysenF+eX/dZZuzs4OX8dFq5FDI9m+VtcGAuUKZ+d94+PjkEu46BFqHOJ"
              "KLasi1J5yIws2bDFeGVxT/zgAFSJzpihRCg8GXMHhqYfv5naPSHEQ5Z92GjuNR0pddD1xKt4l9VBNQpo"
              "bw0x5pid2MT0PFdu1glJY72Jous8GU08jE4bDrDqIGxIho6z5MOmeiN2tyZi5hHQFt+tRnW6us0Bu00C"
              "FFw+Or/sPr88f3nWcReUH5nqXXTbx62TwcteNyN8MKUr+YFNFovT67cu+4Ne/7j91Tcfm2aU1/9nmmAm"
              "DSmgobWo+y9L/lcrtWbU/1dtVDfy/8HJf1eyHlqmog4V20OJtcpvTzK73rwA7oEwjXWeJFbF96IIykPj"
              "nf2yTcKCMpq2LeIM82P6su7XdC9zFObk0O0u91Wmy4pi0VM5wt68S1FFnuZQMf9jnm2CzbOx/xDz1Ylm"
              "LCwHMvh/pfooFv+x16hs+P+DtP8URIFyhyLzCKFDxAQKfQO2LalRLG3o70HRf4uvM0g+7ZraTvntRF9H"
              "Hxn0v7fXjOh/1Ualsdn/vZfn8TNYZALEiDT7pFAtVwpgN/JsDk8KM+d6Z7/w7OnW44nACQLFDftAcIQn"
              "hbHjTA92d+3hmE4UTPXtaniTXWX6Ztei9q54V3jKLcTHMzBRd6beoWiXuxxgUtMnBbcFv0D5stvuHr/q"
              "Dg7Pz/uDQNz87tMlG4wbkmttLGiQrtDwxXmvPwi6MXorNMYT4Q5aJ10wZV8fn3XOX6/Q2tcvu5ffQGMn"
              "g4tW+6vW8y4fGm8tsHvsn98XLSq6bt7ijsxs+qSASXIKsSJ4SO9J4YcTbTpRprvod1BmBmaxjhfVMf8u"
              "lLXZjtQuHvHDIccLMnX4OKnhAfscr2XPpij+7EtHTxqsA2hP2QjmOt3t419lz3XjYjyHihs3Ec5/EQR0"
              "OXj5eEFakL7FEVE1Op5gmVvNUM3bnnntHBvTmXNqqriI6k+A010ohrwOBwUvamuYQaNvTgvhc+WPudm0"
              "wxO4xs+csykmYg+vXOZlyri55uFfqJGh2FlLb8YtVT5pvTxrv+hexhp7vJsw3Me77lIsujyhsJKs9WHH"
              "upIKDfWZSo8sc4KqkOHYacsZXxo3CkRe3jBFlre0RlPxtnw003V7aFFq+GS9ABJHt+4fLKjSocCzTEQg"
              "IPJSpAEgMSmGfBA+W5Wy2kPg1fLEHbk4xDpJWAnOSQCiLJ1obmJkHyfUUXZUxVHi8TK5x1FIrOtmoYR1"
              "Bt1lN1R5IGoPQDRca6PQuB/vio8LLr/E25OwUjz3SRpC56KR66jDBw+zAgFMKV5Z89KOIcHUMgHBnHle"
              "cIPVd3F5fgGawzdB1WZw9Lw36L08RB98MvhvFH0Gjfn7GSzUIBvSlmtWZoM6ZFQuT2SdLlPeWp1TkE1L"
              "0NbCaAxwVZlVPGBGdW4UDlYauHCK09xqtI6mPpfVQbgMRCqhRcStO8JFVzfo910DBa2dHYY1mgTjZHH4"
              "PN4NKNDw7vGua3s9vWv7H601Hjrq6UgD/LCiIyDV/q82WbB32P5vPqrvbez/h2T/B5MYr+ADYBguqk+n"
              "earuKDPH5PV8NQ9HMbjVVGf8pMBuwRrwbArScjy3d1rBQI75JwWAhYPJysJFrrzT1E8K/6FSq+xXH3kO"
              "jU93dkj//IK86LY63UuyI/JxhWAWN3OhoR9+oamC4MDcekEVVW7lpk83Zcq3ljIdiN22eOHQtMfw17eY"
              "60aPF5zyxN4vvCKAKHvqNLEgTAZK1FJKHJqOY06gUEVWSGQgf1JAjR/s8/CSJC/Lo+qXtXbI6pYuQTJw"
              "Q6NZGK6ydkWFqryUHPEiksM73ZCkHoTnkDy2pSYUspdgJE+i2fTO8UBTeh2WOgAW6Ig96WUxTynA65E9"
              "zSiHNtuTwpWpq3Fhmwkyj/qcG052vdmVg5E3hYcCZXZYrEcVchi6bZ54xyDygby+f9g52s8F8iqAPKyW"
              "B6knSFVS8MZAe+UwI+j8uqPMC1urgHRpKvQQ9lfkDOskl0pD0QRYScsEGdIP3eip3avRYKrpeoJtEueu"
              "+0l8SJR9JVjFk0Ijg2NNFGukGV0cDnLssDMj3zo6N680GBUwZJYd4j0v5T//jjT2K+TVRfZa8sQ0y69l"
              "lM18XxYcCDeYiPc9L/hvfkleK+yapI+Rdr09GBmzZZpl66x/vNM57vUv+cEU8vXL836XHGJm8yWVza9n"
              "pkMPMRD1QaqbYaWuVe3W9/PppI0UjdMH+6OFVM7c5HNvBPHX/0QycbxmL8vrOVowDCk8QI2ZA+E1S0vP"
              "rqgZWqbODsWpOrVtfb7Ng53R20MU4GLs9lMC+EvUOYZCawaxobIxpOVsjnLY6u4dddYiQZgIHcqL8b0K"
              "pOBUV5aua1Ob9UgNdVnOfgYFc6/unWExjoJ89/f/79qEeGUlIS54BDtNwTl4Nl/GLUzSbx32CN7fAX8E"
              "ufGRpUxoAjNegcFKreUY4QTxgvkmWoekekD6x6eBIbKvPUY92XjDUmSi376vXOXBG/mkFvLNxHY5ND5Q"
              "dOd6ztyw1Zdo7C8z0JXNuBSnUgoKCs/K0/jlHmwpwUzdcZQrYt9q7GbvA26IE7Y45MYOXCu6I0kLnw6i"
              "ZcG0NKgW0g4W0tiGiqWmV/XgHVOoUxVrz3FVk69SuvshjTHzC2PbuH6FzIoZQngtK5NfOCfz+e9+/a+Y"
              "sCeApPlqZnmMMlSffOWTpIKsQkQ/zK6QrnYujNDMBAmJ/HVhnMcxPh6sk9yx3Cwthng8x+lHg3jSUKsk"
              "/15Y4nS51dk6IG1M2Us+J53jV90VxUvEIGVcr0fZTmrhAcslmVUYgxjGH5GeENBSOOWD1bLO57WS4EJi"
              "WdJr1K5epIklpLtUwtcXYFQRKd9IlvL5+G4S70UkwUQqw5Q1WBUBVkYCqTvurwkfNyZ7fwNt5q+eV6jn"
              "tbJX5rFZ/qSaOl2oss9zm3lrLinwV0e+I4vSI928/cDQD7ceYeQ7OHRMG2CoV/PFMTBLuq+KgetHJpkA"
              "zyXEPbHU1qzhTFcsnoaS7doKvbwN7DRZTl1Snd2qlVNSRSU7Y/ssh93Mou1cjDuMbLW9ZRTNxWrdjZQC"
              "gMs2lNMt/zsSVLm0jQdF8aIBviLHxgVT8mT+0RUdMHmU7hTI5ufECQ73HtVB8aXquTVSDM2evNLsWdY4"
              "17FQa1ksGYv+yz9brA5nrs296JbF2iHtciEQGyMq2cv+gKDMpkDqB6Q1pW/JCb3RFGesGIs1k+ZizykR"
              "K1kScWm9bMmN2QWl8r46Xbi+L5hri9QO8W0WIVdT7xrjXZ5yFjoV94Hh+qE+o+T1WNHpqoiex/BIQPT6"
              "vSB6HEfqd44jzCvL8pqq5q3xwWJJrXlQqdw3WtT37gUtrgEkR8pE00EjmZiGaU+VIX3YnKdDp874GG+A"
              "VxzT+mCxik3jAG9/n5DvfvEb0rqa27aikz8xDbocsiUFZK7D/Exf9OrdLPoDW7FiX5mSodD0xLXcU0ze"
              "DOCnpeXWbK/xqLF/uMyafWknm+4y811eJmyCpxn57jVjpD3WpnayUe/rQAkhAOvwva/NCc2DfK4Uy35S"
              "MFIpL4+R/BHZyEne+af5aDzOuIeANtXmpJBnirmmEaHOUNsStpjXL5oVBZixG5YcM7sf/BwNqMt7/mBB"
              "gNfuEOC1JIALped7CfDGHQK8scHwOMD3KncH8FDbG4BzgH95hwD/cgNwidCs3SHEw42/f5CvA6b5NF+Z"
              "npqm/x5qI3JhaYAMc8Jv/0nWgcWVUgtFTGGAcAdzcd+nstxsqNP8oU+/+iUP0Dk+65+TTrd7QY7O2y97"
              "dx5317iT8Ccfofsabv/8h8re4V6aszrdAthLs4F59I5iAV4SlsPdYGcH2gr0b1M9GZNyR9+9tzAesWvA"
              "tppiUzy4c9yo3wluSJd4P3WFP3C793tivKYL4lAqirgwVixvK5VtGiRJ5WqlIlEj0sWxfEs5cds4ZySb"
              "JBKgkq3hPM10R8VVljXrJWyvV0Lvtf0Mt9e9jdDfO8pnBUePwy+rLd7L5JqVyReEaSO5dMPItm2mwpsn"
              "smgJouyY+nSsGRuyvEuy/B8PmyxjOPDR0CRuFH1wJPkjquvzDUHeIUH+/t8eNkEyDLjW7PFHSJKN5oTv"
              "235QNNmfWc5Geb1bKflfHzZRtr7FLewoInw8ohLo8pLS6w+KLNu6eWuEGeWGMtdPmf/4sClTggUfDVnW"
              "QYNtGXSC/qYPiTJ7VBmblv3hisyHoaj+4WFTXnyVPxrCq4I8PFFGpmncC93dxcbcwrQeOmJ+eEAO8Yj5"
              "yXGvTz4nF5fdXrffW+9Jcy8lwId02jy1yo3m3mbwpDDimwTJu1sXFrWpg5e04U6QaX34e1rf/fafyNcz"
              "bfiGnUd2J3jwgaYZkW5p7X3MW1pLbuRWNqGcGVEpU0YJPRMvATmlqqYU7k5r+Jt/JbwjwnoiHeqYbwtp"
              "h82WVJVCESuV1IiVZrqts5cQ0FLNI0qzoP5cmcBY7hDgf/EvBPqgNvlcmUz/I3mlqdRcMULoQ4b3qfKW"
              "Xbh2dwD/7X8n0Ik2mU2YnGFHpeSipFE/anbvG94LAHT9gVddVXNwhfKHUgFfghEMx63p1L7XUKpGrlCq"
              "MQs1+vd/+M2fEz5OosBA8TAJao/lcnkB7eIFD1vKOkKyilaSiGI2G3zuDATJuXTXFeKTLMuT9ZsV8iTd"
              "o16zdJ6k7Lsu1qoYLZczxrlBSmWHRHOcm18iXdxaVan8aePi5kSFmNekwuicqosnlslzum9RYyLNoEhl"
              "9BkBrolBrsw2bOn6e0kNVN9Tp4ssGLP6cg92mWQ+8RDUdqO1111odpKs/OtetrYObPJDWbWXhv4e1o3f"
              "D7RaKiXR+tuyRYfzoY4XF9LbMsBxRJ3ypXi3WCpO6+be9aDFhJtBbYeqXBEEPaHrXrvHL6XMk1syz7fH"
              "u1JV00thXTsgra9fti6PX56SXrd12O0sn8y69dOZYmmzyfvLZx1z222yXidmvT7RbjB1v4hbB5X8iqqE"
              "p8CROodzpCxLcA+7eMEavxffcK1WyUpAvY4s18m5xZbOK7ZE0mHMdoWLF73q7oH6ltlhGoF8bdNSdIF7"
              "i5lxWTrhupzL6edaerfaZBKgIjcZlp29BRBfxwlrIzW8/s6Cy+v7dtzRJM0SlyjosyaWEaJ8ZwG69Zpk"
              "aoqujcS8WBoPPrXkQkzJlBYKJoDJiASpV9JyTmbBLz127Y4jt5Ih4zK1LAiKa0BSYChKpEDRY6DNVQAp"
              "Ccu8p9DUemU9sMzCRva9kQ3H2kpwzIzauruYpVoit/JduWtDyEYl83zjpYa3DRFFs8jV7AoUiaUEAK9a"
              "vUNw/vPvpN7tvRXQkoM96OVMgWjMO7kUhGr3D6HaChByTKDH82uYQhYvDwMpUVzkyF3EsPIYV4bdOU7J"
              "EQXt3ldPUo5xp7lKZC4SbNlr+F60+8Z+ltoduNeSTTymnhW/qOJ1l6XsZvLsGywUmZDsSem2mt0vl7En"
              "EmMZxPF9c0IJoIw2xOtiAPHk655qeSxrPKwcvCMi1GbGG2qQPiygzRaQb9GyqSXFpay0ihnH75da8QU3"
              "anjuMToEGwmDiqoH5Lmi6zSJbLODOrEt0UQhD02uENYZ2KxZPn6zFlRgErd0sk+u5xUzaxcmv/6f3/3i"
              "z7/723/8P3/4dW7VOqDBVWtpUlK63vHdocVGHtvlWehW9fsNWuUs4UID8qAkhtc5I1jrS6daufODKsYQ"
              "IU6Q/vWdoTVDdzGZ8umOBCe41ZwxGcFYoZhmJBzGEhczLBrXkCumIVlXw3SlQxN0aGdmZ3Cd1WHV7h+/"
              "6uaLjYpG+C6y+PlCb32ejd51R1cMR7NXYdpuGxuufS9c++82/PouaJQhMV6QcjnTkG/rumLZHxHDFgIJ"
              "EAIohEz5/Mi1ZU6IM6ZkMnfGuAYE6twawMqHQBgPlWFncZyPlmPXD8gFFNdJW1cmq/Bs1sqGYd8Hw/5v"
              "v99w63VD9WQ2AQjYiAUBgviIuPVzTUHlGqncGSsOsegNVXSbKGSkm7fozb3STD0AhWmYoB8Wv07lNivD"
              "6uUZu6S0WN3nTrOlTtLdJdduHLina1dSs6MHdDdM++6Y9q/+sGHa64ZqF2NMLW0IyrXxxqOII43q6kfE"
              "uc/Q8WFTBV6zCdpkapk3GhIGscdUBwog18AUhun5BB6Akp3Ob9bGtmuNB8q2mwfkxRyaB/PImoBl9Arl"
              "7AoM/JWUcD9Y7v3+PCD/suHNazd4xSVHMYT/iDgzXoK74wCFDcfkxtSHigGy6AaJ+krThVZ9q1gTglo1"
              "Rv7x/XwynFlIlg/WfZ3GV9bGpevN98Sl1xFGXj8gvX4rkldioeBxhLS9iRz/ECLHO5o91KY6CxsHUU6T"
              "77rOn1HkQ0gKso6Q8ezA9Gj+oyXjQdYZX+4vOFvvBx9i/mXjs8WiybMu642z3cb+eqPJP5TMMFHav/OU"
              "MM27TwnDgrcbqUGeH8rydN8O6RR5GihXqI2R8yHuuB2Zw5kbM3VJbZBzoKPROz9xUV34+HroItXlzMvX"
              "lL7R52LKh4pF2mPFcjbi6U5PNK1F4rxn2hGIg4nGyQvNdkxrToqnmjFzqF36mG5zqdbWlxsictSPw/A5"
              "QH98r0dvq41KntQaqyeUuGIw/Llw1QSdQUszrN5swq7WOqXMd/vc0j5sZTr71plV0o/kWueVuEH+TBdL"
              "MOsVGbacaTfUReVsjszEd+4t6puAIlxOU3Wtrp9M1w7rmvX8wpxZ9h3eMTgmue8uDUxuP9Wnk63ELp+J"
              "YUOZa6fM9+mQBV3GJp3ErNN3RV89att4zR/ehqdTh6p3R2H7TGGzF44kuw8Suw/Pa+OAXFyeHx2fdMnn"
              "5EXr8HgVJ+yFZV5rOt24YT8EN+wL5UpjWYdZzuWNgfveDNxNMr2Frc91JdP7ELPhdRRNn4ccc5ySF0+M"
              "l+VmWPRUYx739XrWLaArsMln+JJX9RKtde2F4lGpfAam+3AIqs7iK5e14bCMQ3UpR1Eu/sruOc/VhCTp"
              "6X5eoowl462vbM20x3T45tB8KwkZumJ4V72DcCE3iuZ3f0tOTcvAoAfmij/E0+dj4YU/1Qz1eqanXGvY"
              "rXX3jyr+tyHOhaq58iukpUPMBkrtDoHy1/8f+bKyw72q5CUABySKNZvi0UbOC3tTS0sKinl/IKnfIUj+"
              "5n+RizHoujtHFqWke0MZyrjxQj3Qx3Gv5oEBpHGXOPI7FiWF51w5sZyYQEIBqQlmysiiSXcPZgBleT8t"
              "N2pxNB+H1p2lBC6nAC6bSXnZfaKH6HbimHxJ2cGR4IbSnW8jNZYNS5AuSUbW3MSMuUgi9xolkp4qN3rP"
              "HIxwsQVZZD97kQy52YwnV1KWgDbdnUydeTL43xvjEaH7JlGRGsZie3VOnTJhabYItGuRa82yHXLNFAEs"
              "+Gn+zC5pdwEsFVq1QMhWzGslz+eyWpZjSYbjB7jOi2U1zuf05G+OLGUSTnjFsxud9/vnp+Ss9er4eYvf"
              "eNa6JMXuW2XokAbpK1c2YfNGpaqnTWY6Hj0oeYJbLqyTLjpjYuxMuSlsLQPpBOg2QyZSblEtM9tcZrO1"
              "uAzPMOGCvudE/SbOkJSrQ8foa5MoteWU5Us7ktNl9gJOyFy8I58FHcH9u978+e7X/5qQyKIqu3ny7vd7"
              "GRYsuk+T+4rJRFm6MLq6+ao/Moy95+VOSoL6fpDPW9NV90HXh2bsxMMGx1a8JO+XDwfH+II+HAQTu7kb"
              "FFsNxf7q/3k4KOYu6bqRTPYu8vcnmyfvo0ynu7Y13J0omrFrUVtYD7uaQycD+Di4YlfevZ3oy/dRgWev"
              "0WA/4Yn+rD3a837n76t7lUbzE1K5DwDMbLDpofvv6fo/fgZLS4Ct2Yy/VcuVAqHG0OT+hJlzvbNfeAYE"
              "FjoTDVUM+0DQLlh8jjM92N21h2M6UeyyeF8empNdZfqGYZV4x9lmXjs0t4Wfyw5dIDRDfgp+K9NlvB8t"
              "lXFe/vHxRBnRkBslJh81vBzqeBi8qVwOv3BYeVI+6mCi7nR/QorUXcj1ki1t0zLa+5DPlskBmSH1Rcqv"
              "NTxTJrn0jmTH0sKeqIi+P52S5EFkOdnzONZz2aQLgOwCSCh2P9I9Qw24S5m+VTBoswxyKht4Mq9rHse5"
              "d3M5cAKdIslEtuekCoq7K5lM2MOrw+gtk4uAMJdGtpupGqXKf5tvIw50c7SKBpAh/+vNvUZU/jcatY38"
              "38j/ByP/G3cj/x+YAF6bWD0xRx3Feb8CokenpLa/TSqPDqpNcnG6NvFav1PxiqCbWWwN3iv4ak1MfWPz"
              "Hc7olXcpJn0W9Gp2uvsm5XD1IjDEG1VPJJc43zMUm/zmeD1lJOvUUdJhKFVUYjCVw5NnF4pc/r1ufWUr"
              "IQri/PTipNvvduQFvJ2ZvcO9YKBqQgKirdwBqHkjRROjQt0DOA/YPZWq/43wcPTgSrHu1v9TrVVj/p/a"
              "o43+9/3S/yoJKlayPz9dscnhv89/ZD5Z9wtyBf+4SC62eqhYImfDvbPUWnOSzkyjkigvM5XqxcGDiI/T"
              "oYJxRgCXo1AYvxwo4fNRSQErUr05HIfC5YY3wJxL11Hm975spzI3YJoSlqU85JaBcc1i7+ELt82ztPxn"
              "dzECT7yH/Z+9R7VaVP5XK5v9n43/Z1FFIMzWa5X96qNUf8zCioIfaBuIMxQ3V47Ic5E3lp/8QOuT9MaY"
              "0dyP4EyULXcsOP79H37z12lSYa9hB/IsvbdhxvLAIRAzrL7I8URJMujGmiTevpoLRkE1gRv+sV2mewJn"
              "f6zZ6IDQAZPZESDNdUUQdWYhqrJQdnHvLgt3Fy7/8spqRl0G9MTI1LxAR1I7wXGyCE1ySVFu4URMl+CG"
              "FqVGzpDpOwN/RsxQbnDkTCOQ4qioNXJ5KqoNdZpnNWqNSHx1qkvunpxs/ePTLrnsnraOz47Pnh9ku9lk"
              "+SGzDJwsR+/iXkrGHBCPPSx+vw7fxkF1f11O8notL+zkWVNguEfKRNOBNiamYdpTZUjX4fL0uUjLcLQd"
              "VbMddu04sI/RTNMd8tOZ6dAc8jq6jl9jvbUetcjD4L/7xf/9eqzpFPk4sdk5FPTaqzpwcX2+zdk7blYT"
              "ZXKl4TRBHljA6ufIMzWD2PzIbvm7X/x9OsdvH3aa3Woqx69liFkNGJI2XItQqFVSuFqQ/YXvG+cLP+Rw"
              "8NY4cnJQdlLwEPhw3+wpxtCZKdZ8vUdqpBEu3t1DvwQh58wsgzim0IxShpFGqLkVn/ipwATHenxd6qF0"
              "nXkg2wUxPgIUnL80dKmud8cq0ne/xSuviTcM0ptZ18BsSLFn6qBnnGIehPYYLwU2RrSUAfJG/ajZXdz7"
              "EhLzxizF9RWAtZcadSUHTKb9P519+61OV3IAZNj/Dfgatf/r9Y39v7H/F43/SDxeuJSJH1B136Pd/nd/"
              "JWFOHkNaQQRwfvQoj238/h0DrxWWneaAcDGB2oth3pIhrLUDKg38ZxDqgWmq2PhGJfbsiul3Nqk2P+P3"
              "GzOVKHo1QIa5e9RuNVvNxfl6Rur+XNolCqCvZ9QOB4TcuX4pkTfS7ZZM5U0E4zBhCiqMwOADUn9E/vd/"
              "IdUvyRPybGUPT20xLO6qmoOwT4Y7dRDuLcO+TVFIl4F6Yz+foS03yMdMIesipAlwriGeEEfbBVjsTHeW"
              "ZwaszAuu7SXt/CX6ImwQDMNxPnVcqutqxnTm9OdTWChjNrmiVk8bGVRdTJHsza4mmnMHK9as5FyxvfSd"
              "RqFMp+mIeDE7zkLkEuK8jtQwBxW5UGx7PQr/ZtNu8yTr/1Ev42pbf3n0/0rt0aOI/t94VKtv9P970f/t"
              "sTKlK2j0Tx/bpq6pfgozV2pz9Xv36WNQsAywL7wSlqJqM1swTPhuO5b5hnqf3eiO4A2bXqPdeqvZwUq7"
              "bNwbxnWn9M8l+8ocYHH6b9aam/i/D5z+65Vu9TCV/muL03+70drrbuj/nugfUwHdh/yv1mLyv76h/w+c"
              "/j1STaJ/tomzIeWHSv/acKArMwNQYMXw/0z6f1SPnv9s7lUbG/q/F/q/oUPHtFZgADHBXdkPim7v2rvw"
              "6xtxJ8prr1L82wu/KrCZKe7EBa9ViZz7CfidnHFHcZQnhdPKdmUMtW/g//EO/PMt8pvEhqIX2Qcaaja2"
              "6zWlWtuu1kiFQLNkh/1xA+3WlL3tPfct/HpTC76B38a1/dCLnb2bnVqk1s4eNHSzsx/rA/7/dlLZ3vOK"
              "V7FJ7LfKygdf7+yxCe7yNX26FP1PtOlEme4oxlydajs3tb3VGUEW/derzQj9P6pV9jb0fy/0r6jKFMP/"
              "drShaaykB/iuTo+CXGHypPBDphfsmhjBMFAV6w0i6rVp0eQaMkk08KswTA+NfqNCrEH+3yj6DH6AUaYZ"
              "I3sN2n82/VcfRff/G83GRv+/H/rPuf8PqGHOrCG1RdAUxw9iKBMgVcwThr8VnrKobRaIG4lVeiwwCrce"
              "/LY29PdQ6Z+x6/WQfxb9V2u1mP+/3tzE/zxo+mf4Icj/dqw5QPtCfz46esyxR1KSi/+ppeEt0lCDq+5Z"
              "5W0Kwl3lNXjodlYNZYjhCNgBix3IKs70ESh8iFsWmaPhEQxY/qjare9llWeh+k/FfkhW4SvTUjFxqNjp"
              "yJwn3ryDpdlZp8yRmBamc4F12jvcP8wqPcK9Yih8eHhUS4Hg1cgDX8YgcB86tJb8FIlXYSMYHhD/d0Dj"
              "p/fF/xsx/2+9vrH/Hrj+N9epIOw+4krZU/0KhEfWuB9OFYdamqLjDcumAR/sckeZn6Fvp3xm8nD8QyWY"
              "LfkxZh8RjTPmcOFKjJAZKeTIY5asJKV2z+c5ofoeL0prwUv/JxLgWMxbFGmJ8eE8rRjKjTZSxIxztYSK"
              "M4A6G+zlo5mu2+z4W3QF/KVJH92tZqjmbaCdp3h2ZLnRdGDFzdEiuODW2N2IgvfI/4Ed7CrsqlBxTxCQ"
              "iXWjDSnGil5ryySCzLL/9xr1MP+vVWrNTf7He/L/Bdd6R6z1uiL8Q43jdZEszNMGXRB+vGbcBhOL0fZY"
              "MUZU/bn/2havUto7olRFnyOPHL0Wfz2nBnCYYVo9XRnBEK7hR4deKzPd+Tn+fmwM9ZlKz0zneIK7D4rB"
              "YrPtcEtDxbikjqXRGzHQNo+gdq+NChVWKfBRbcqPG/yQO0B2PWdJqKhhOtq1OKaNZ0LNGQs9RW54//Sv"
              "UkbwijrRjIFFh1S7WWUTMHP/vxL1/+8hS9jQ/33QP1/rHbbWK7n/Zza1d6amrg01kNro24dmWQAzOuoj"
              "X3eD3W5E/AOS/4qhTYQueq2binMP8T/NZj0W/9Pc7P8/KPvPps46YgTYJdrABvBiQxCJnnxGpNPZiYRB"
              "sIhf0aJTqjinpgqi3qI4Xhr92MbDYE8KGmipBnNIciPFsRTD1vGGZm/P3zInf9yhOu7sBy5fdkz3ZShS"
              "AUt/IyvtvtzhJ3E9oS+y9+IZnkpFmDMAvqcfEP1fza6udDqwNJveB/3Xaxv6/37Qf5iMEfTOSmTsEWaQ"
              "AgOk2ajISbNWEaTJb7vVp2Ml1G4L30Cz5XqwWfGWAUlC7pWHT+456f9WuaED+1aZ38v+fyMu/5ub+J/v"
              "Af0vIsYt04kSf4eOLIrehJ0QlXqvA2+n2o3p/DFa1J9FXn7DCPczKUHvfYAEvR75r5n6DCwzauM+6mA6"
              "01dRBDL9f/H73x7Vqxv639B/gP7toaJHVPgevkIhvd8MafHifbVcbUbU+IQa30hrpPKMppxlfJlTrWjm"
              "Vyu+vFMmlCv+PxB1uQwXyIz/fVSL+v8rjY3+fz/0/+HH/4tsjrKw/Xplu14ZN/ZvGvvjncb+wtHx30P/"
              "X2r8/2ApHrBw/H+t0qhu4v/uh/438f+bZ/Nsns2zeTbP5tk8m2fzbJ7Ns3k2z+bZPJtn82yezbN5Ns/m"
              "2TybZ/Nsns2zeTbP5tk8H/Tz/wNAEHsmAIACAA=="
          )
          tar = tarfile.open(fileobj=io.BytesIO(base64.b64decode(raw_b64)), mode="r:gz")
          tar.extractall(".")
          print("Successfully deployed 35 Deep Ocean project files!")
          '

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"

      - name: Build Debug APK
        run: gradle :app:assembleDebug --stacktrace --no-daemon

      - name: Upload Ocean Sanctuary APK
        uses: actions/upload-artifact@v4
        with:
          name: FocusLock-v3.6.0-DeepOceanSanctuary-APK
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 14
